testMode: assertion
testLimit: 100000

deployer: '0x10000'
sender: ['0x10000'] # to have a different sender of TXs then deployer

corpusDir: "corpus"

# fixes the issue with a constructor on:
# revert, out-of-gas, sending ether to an non-payable constructor
#codeSize: 0xffffffffff

#cryticArgs: ['--solc-remaps', '@=node_modules/@']

# format: "json"
